### ISSUE TITLE
日志乱码

### ISSUE THREAD

**Issue by zhangweijian97** [hjhjfhjhujhh/Arknights_24-7_script#2]
如图
![image](https://user-images.githubusercontent.com/52686008/168506482-8318c4e6-b793-45c4-84bf-707a9bc4b42d.png)

这该怎么解决？

**Comment by hjhjfhjhujhh** [comment]
把日志文件一起上传啊...
你换个编码试试？

**Comment by zhangweijian97** [comment]
解决了，不上传因为就这么长😂。我试了下GBK编码，就好了。原来默认是UTF-8，就不行
